services:
  nous-backend:
    build: ./backend
    container_name: nous-backend
    ports:
      - "3000:3000"
    networks:
      - nous-network
    environment:
      MONGO_URI: mongodb://nous-mongo:27017/nousdb
    depends_on:
      - nous-mongo

  nous-mongo:
    image: mongo:6
    container_name: nous-mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - nous-network

  nous-nginx:
    image: nginx:latest
    container_name: nous-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nous-network

networks:
  nous-network:
    driver: bridge

volumes:
  mongodb_data:
